# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: install lua5.4 liblua5.4-dev luarocks
        run: sudo apt install lua5.4 liblua5.4-dev luarocks
      - name: Install luafilesystem
        run: sudo luarocks install luafilesystem --lua-version 5.4
      - name: Install aspect
        run: sudo luarocks install aspect --lua-version 5.4
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: |
          git submodule init
          git submodule update
          cd .src
          lua5.4 run.lua
          cd ..
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
